backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: 'Posts'
    name: 'posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{uuid}}'
    identifier_field: uuid
    fields:
      - { label: 'uuid', name: 'uuid', widget: 'uuid', required: false }
      - {
          label: 'Publish Date',
          hidden: true,
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: true,
        }
      - { label: 'Text', name: 'text', widget: 'text' }
